apiVersion: apps/v1
kind: Deployment
metadata:
  name: gawudgr


spec:
  replicas: 1
  selector:
    matchLabels:
      app: gawudgr


  template:
    metadata:
      labels:
        app: gawudgr


    spec:
      containers:
      - image: okteto.dev/gawudgr:latest
        name: gawudgr


        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f2634721-41a7-4b67-b17b-cd91e1a572e5"
        - name: Vless_Path
          value: "/vlqw3dadiw3w"
        - name: Vmess_UUID
          value: "f2634721-41a7-4b67-b17b-cd91e1a572e5"
        - name: Vmess_Path
          value: "/vm73wdzsduk"
        - name: Share_Path
          value: "/v2link"
